version: "3.5"

x-app: &base-app
  build:
    context: .
    target: app
  depends_on:
    - database
  volumes:
    - ./src:/src
    - ./tests:/tests
    - ./deploy:/deploy
  ports:
    - "8000:8000"
  environment: &base-app-env
    SECRET_KEY: 'insecure'
    JWT_SECRET_KEY: 'insecure'
    START_STUNNEL: 'false'
    DEBUG: 'true'
    USE_JWKS_TEST_KEY: 'true'
    IIIF_IMAGE_SERVER_WABO_CERT: dGhlIGNvbnRlbnRzIG9mIHRoZSBjZXJ0IGZpbGU=  # This says "the contents of the cert file"

services:
  database:
    image: amsterdam/postgres11
    environment:
      POSTGRES_DB: iiif_auth_proxy
      POSTGRES_USER: dev
      POSTGRES_PASSWORD: dev

  dev:
    <<: *base-app
    build:
      context: .
      target: dev
    command: python manage.py runserver 0.0.0.0:8000

  app:
    <<: *base-app
    build:
      context: .
      target: app
    image: ${REGISTRY:-localhost:5000}/${REPOSITORY:-opdrachten/iiif-auth-proxy}:${VERSION:-latest}
    command: /deploy/docker-run.sh

  test:
    <<: *base-app
    build:
      context: .
      target: tests
    environment:
      <<: *base-app-env
      DJANGO_SETTINGS_MODULE: "main.settings"
